import Head from "next/head";
import Image from "next/image";
import { useSelector } from "react-redux";
import Loading from "../components/config/Loader";
import Header from "../components/custom/Header";
import Banner from "../components/homepage/Banner";
import Members from "../components/homepage/Members";
import Popular from "../components/homepage/Popular";
import Success from "../components/homepage/Success";
import Work from "../components/homepage/Work";
import styles from "../styles/Home.module.css";
export default function Home() {
  const { user, data } = useSelector((state) => state.auth);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />
      {data ? <Popular /> : <Members />}
      <Success />
      <Work />
    </div>
  );
}
